# Generated by Django 6.0.5 on 2026-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportworkers',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
